import os
import pandas as pd
from dotenv import load_dotenv
from google import genai


# ============================================================
# CONFIGURATION
# ============================================================

load_dotenv()

API_KEY = os.getenv("GEMINI_API_KEY")

if not API_KEY:
    raise ValueError(
        "GEMINI_API_KEY not found. Add it to your .env file."
    )

client = genai.Client(
    api_key=API_KEY
)

MODEL_NAME = "gemini-3.8-flash"

DATA_PATH = "models/investigation_cases_enriched.csv"


# ============================================================
# LOAD INVESTIGATION DATA
# ============================================================

def load_investigation_data():

    df = pd.read_csv(
        DATA_PATH,
        parse_dates=["timestamp"]
    )

    return df


# ============================================================
# BUILD CASE CONTEXT
# ============================================================

def build_case_context(case):

    evidence = str(
        case["investigation_evidence"]
    )

    evidence_items = [
        item.strip()
        for item in evidence.split("|")
        if item.strip()
    ]

    shap_features = []

    for rank in range(1, 6):

        feature = case[f"top_feature_{rank}"]
        shap_value = case[f"top_feature_{rank}_shap"]
        impact = case[f"top_feature_{rank}_impact"]

        shap_features.append({
            "feature": str(feature),
            "shap_value": round(
                float(shap_value),
                4
            ),
            "impact": str(impact)
        })

    context = {

        "case_id": str(
            case["case_id"]
        ),

        "transaction_id": str(
            case["transaction_id"]
        ),

        "account_id": str(
            case["account_id"]
        ),

        "timestamp": str(
            case["timestamp"]
        ),

        "amount": round(
            float(case["amount"]),
            2
        ),

        "fraud_probability": round(
            float(case["fraud_probability"]),
            4
        ),

        "risk_level": str(
            case["risk_level"]
        ),

        "investigation_priority": str(
            case["investigation_priority"]
        ),

        "merchant_category": str(
            case["merchant_category"]
        ),

        "merchant_country": str(
            case["merchant_country"]
        ),

        "device_type": str(
            case["device_type"]
        ),

        "device_known": int(
            case["device_known"]
        ),

        "ip_risk_score": float(
            case["ip_risk_score"]
        ),

        "is_foreign_txn": int(
            case["is_foreign_txn"]
        ),

        "velocity_1h": float(
            case["velocity_1h"]
        ),

        "amount_vs_avg_ratio": float(
            case["amount_vs_avg_ratio"]
        ),

        "time_since_last_s": float(
            case["time_since_last_s"]
        ),

        "account_age_days": float(
            case["account_age_days"]
        ),

        "has_2fa": int(
            case["has_2fa"]
        ),

        "card_present": int(
            case["card_present"]
        ),

        "rule_based_evidence": evidence_items,

        "shap_explanations": shap_features
    }

    return context


# ============================================================
# GENERATE INVESTIGATION SUMMARY
# ============================================================

def generate_investigation_summary(case):

    context = build_case_context(case)

    prompt = f"""
You are an AI assistant supporting a financial fraud investigator.

Your job is to summarize evidence already generated by the
FraudLens fraud detection system.

IMPORTANT RULES:

1. Do NOT independently decide whether the transaction is fraud.
2. Do NOT change the model's fraud probability.
3. Do NOT invent evidence or facts.
4. Do NOT claim that correlation proves fraud.
5. Clearly distinguish model output from investigation evidence.
6. Explain technical model signals in simple language.
7. Give practical investigation focus areas.
8. Keep the response concise and professional.
9. The final investigation decision belongs to a human investigator.

STRUCTURED CASE DATA:

{context}

Return exactly these sections:

INVESTIGATION SUMMARY

Write 2-4 sentences summarizing what the model output and
available evidence indicate.

KEY EVIDENCE

Provide 3-5 bullet points using only the supplied evidence.

MODEL EXPLANATION

Explain the most important SHAP-driven factors in simple language.
Mention whether each factor increased or decreased model risk.

INVESTIGATION FOCUS

Provide 2-4 practical things an investigator could review next.

LIMITATIONS

Explain that the model output is a risk signal and does not
by itself establish that fraud occurred.
"""

    print("\nSending request to Gemini...")

    try:

        interaction = client.interactions.create(
            model=MODEL_NAME,
            input=prompt
        )

        output_text = interaction.output_text

        if not output_text:
            return {
                "success": False,
                "message": "Gemini returned an empty response."
            }

        return {
            "success": True,
            "summary": output_text
        }

    # --------------------------------------------------------
    # RATE LIMIT
    # --------------------------------------------------------

    except Exception as e:

        error_text = str(e)

        if (
            "429" in error_text
            or "Rate limit" in error_text
            or "rate limit" in error_text
            or "too_many_requests" in error_text
        ):

            return {
                "success": False,
                "error_type": "RATE_LIMIT",
                "message": (
                    "Gemini API rate limit has been reached. "
                    "The FraudLens model and investigation data "
                    "are still available."
                )
            }

        # ----------------------------------------------------
        # NOT FOUND / MODEL ERROR
        # ----------------------------------------------------

        if (
            "404" in error_text
            or "NOT_FOUND" in error_text
        ):

            return {
                "success": False,
                "error_type": "MODEL_ERROR",
                "message": (
                    "The configured Gemini model is unavailable."
                )
            }

        # ----------------------------------------------------
        # OTHER API ERROR
        # ----------------------------------------------------

        return {
            "success": False,
            "error_type": "API_ERROR",
            "message": (
                f"Gemini request failed: {error_text}"
            )
        }


# ============================================================
# MAIN TEST
# ============================================================

def main():

    print("=" * 70)
    print("FRAUDLENS - GENAI INVESTIGATION ASSISTANT")
    print("=" * 70)

    # --------------------------------------------------------
    # LOAD DATA
    # --------------------------------------------------------

    df = load_investigation_data()

    print(
        f"\nInvestigation cases loaded: {len(df):,}"
    )

    # --------------------------------------------------------
    # TEST CASE
    # --------------------------------------------------------

    case = df.iloc[0]

    print(
        f"Testing case: {case['case_id']}"
    )

    print(
        f"Transaction: {case['transaction_id']}"
    )

    print(
        f"Fraud probability: "
        f"{case['fraud_probability']:.2%}"
    )

    print(
        f"Risk level: {case['risk_level']}"
    )

    # --------------------------------------------------------
    # GENERATE SUMMARY
    # --------------------------------------------------------

    print(
        "\nGenerating investigation summary..."
    )

    result = generate_investigation_summary(
        case
    )

    # --------------------------------------------------------
    # SUCCESS
    # --------------------------------------------------------

    if result["success"]:

        print("\n" + "=" * 70)
        print("GENAI INVESTIGATION SUMMARY")
        print("=" * 70)

        print()

        print(
            result["summary"]
        )

        print("\n" + "=" * 70)
        print("GENAI TEST COMPLETE")
        print("=" * 70)

    # --------------------------------------------------------
    # FAILURE
    # --------------------------------------------------------

    else:

        print("\n" + "=" * 70)
        print("GENAI ASSISTANT STATUS")
        print("=" * 70)

        print(
            f"\nStatus: {result.get('error_type', 'ERROR')}"
        )

        print(
            f"\n{result['message']}"
        )

        print(
            "\nFraudLens can continue operating without "
            "the GenAI summary."
        )

        print("\n" + "=" * 70)


if __name__ == "__main__":
    main()